title: MCOMP0001
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs

url: https://pypi.org/project/META-TOOLBOX/

aux_links:
  PyPI repo: https://pypi.org/project/META-TOOLBOX/

color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Importante
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

enable_copy_code_button: true

footer_content: "Copyright &copy; 2023. GPEE.</a>"
